### ISSUE TITLE
Write a server

### ISSUE THREAD

**Issue by noporpoise** [mcveanlab/mccortex#16]
Write a server command to respond to queries about kmers and links. Requests would be HTTP and responses in JSON. At first the server would hold the graph and links in memory and the data would be read only. Javascript apps could then be written to visualise and interact with the graph.

**Comment by iqbal-lab** [comment]
This stimulated by GA4GH? Is a good idea.

**Comment by noporpoise** [comment]
Brought about through debugging and Kiran's visualisation. I got something working quickly that just takes interative input from the user at the terminal:

    mccortex31 server -m 1G -p links.ctp.gz graph.ctx

You type in a kmer and it tells you everything it knows about it. Adding HTTP/other requests would allow anyone to write third-party programs to visualise the graph, use it for genotyping etc.

**Comment by iqbal-lab** [comment]
V cool.

**Comment by noporpoise** [comment]
Addressed by e458358d. Start webserver with `scripts/mccortex-server.py`.
