### ISSUE TITLE
missing tab means Bandage can't read mccortex GFA

### ISSUE THREAD

**Issue by iqbal-lab** [mcveanlab/mccortex#26]
Not sure what the spec says, but Bandage expects a tab, not a space, after the initial H on line 1.
Currently Mccortex outputs a space.

**Comment by iqbal-lab** [comment]
Actually Ryan Wick says the spec requires a tab

**Comment by noporpoise** [comment]
Just fixed in develop branch. Thanks Zam.

**Comment by iqbal-lab** [comment]
OK thanks! Should I used develop then in general?

**Comment by noporpoise** [comment]
Yes, probably best to use develop. Develop occasionally breaks but is more current. Master shouldn't break but is missing latest commits.
