### ISSUE TITLE
server occasionally returns invalid JSON

### ISSUE THREAD

**Issue by Phelimb** [mcveanlab/mccortex#28]
E.g.

TGCCGGCGCGGGTGGCCGCCG
{
  "key": "CGGCGGCCACCCGCGCCGGCA", "colours": [1],
", "right": "C",
  "edges": "02",
  "links": []
}

Looks like it's missing the "left" entry partially.

**Comment by noporpoise** [comment]
Hi Phelim,

Thanks for spotting this - it's a bad bug. Uninitialised memory was being accessed. I've pushed a fix on develop and master branches.

To update:  `git pull; git submodule update --recursive --init`

**Comment by Phelimb** [comment]
:+1: 

Thanks Issac. The server is a great feature.
