### ISSUE TITLE
server occasionally returns edges that aren't valid ints

### ISSUE THREAD

**Issue by Phelimb** [mcveanlab/mccortex#29]
e.g. 

ATGCGTTATATTCGCCTGTGT
{
  "key": "ACACAGGCGAATATAACGCAT", "colours": [1],
  "left": "AT", "right": "A",
  "edges": "a3",
  "links": []
}

I'm not sure if this is intended behaviour though?

**Comment by noporpoise** [comment]
Edge coding is explained here in the wiki:

https://github.com/mcveanlab/mccortex/wiki/McCortex-HTTP-Webserver#hexadecimal-edge-coding

It's a compact way to specify each samples' edges using only two characters per colour.
