### ISSUE TITLE
Use of -G option of contigs command.

### ISSUE THREAD

**Issue by yeban** [mcveanlab/mccortex#46]
What is the `-G` option of `contigs` command used for? Does it impact assembly quality?

**Comment by noporpoise** [comment]
Genome size, along with mean read size (stored in the `.ctx` graph file) are used to calculate contig confidence. Genome size can be guessed from number of kmers in the graph if most of your genome has copy number 1 (e.g. humans). 

If you are not using `-C, --confid-cumul <C>` or `-T, --confid-step <T>` then it is not used. I'm not sure that these are required as McCortex assembly is quite conservative. 

There is a bit of documentation here:
https://github.com/mcveanlab/mccortex/wiki/Contig-Assembly

I'll update it now.
