### ISSUE TITLE
Help output shows version 0.0.3.

### ISSUE THREAD

**Issue by yeban** [mcveanlab/mccortex#50]
I am using mccortex compiled from git (SHA: 22e27b730d316c148c537e1f81753bad43cd0cc8) using `make all`.

**Comment by noporpoise** [comment]
Running `mccortex31`, you should see something like:

    ...
    version: mccortex=v0.0.3-548-gfbe7376 
    ...

Meaning we are on commit fbe7376 (`g` prefix means git) which is 548 commits ahead of version `0.0.3`. If you are seeing only `0.0.3`, you should run `scripts/build/update.sh` to update. You can check which version of mccortex is being called with `type -a mccortex31`. 

I'll close this issue, please re-open if the problem persists.
