### ISSUE TITLE
What does mccortex build do if it encounters Ns in the read?

### ISSUE THREAD

**Issue by yeban** [mcveanlab/mccortex#52]
Are k-mers containing N automatically ignored?

**Comment by noporpoise** [comment]
Yes, sequences are broken up at N bases.

For example, the input `AACNNCTA` gives kmers `AAC` and `CTA`:

    $ bin/mccortex31 build -q -k 3 --sample Test --seq <(echo 'AACNNCTA') - | bin/mccortex31 view -q --kmers -
    AAC 1 ........
    CTA 1 ........

**Comment by yeban** [comment]
Thanks.
