### ISSUE TITLE
Error message during installation

### ISSUE THREAD

**Issue by abeu9727** [mcveanlab/mccortex#53]
We are getting this error message during installation. Any ideas on how to resolve this? Thanks.

make all
cd libs; make
make[1]: Entering directory '/home/microstaff/Software/mccortex/libs'
make[1]: *** No rule to make target 'xxHash/Makefile', needed by 'xxHash'.  Stop.
make[1]: Leaving directory '/home/microstaff/Software/mccortex/libs'
Makefile:324: recipe for target 'libs/string_buffer/string_buffer.h' failed
make: *** [libs/string_buffer/string_buffer.h] Error 2

**Comment by noporpoise** [comment]
Did you clone with:

    git clone --recursive https://github.com/mcveanlab/mccortex

If you missed the `--recursive`, you need to run: `git submodule update --init --recursive`, then try `make all` again.

**Comment by abeu9727** [comment]
Thank you for you help. This has resolved the problem.

**Comment by mbhall88** [comment]
I am seeing a similar issue. I am trying to install in a Singularity container running Ubuntu Xenial and am getting the error log
```sh
$ make all
echo '#define CTX_VERSION ""' > src/global/version.h
mkdir -p bin
mkdir -p build/kmer31
mkdir -p build/global
mkdir -p build/basic
mkdir -p build/paths
mkdir -p build/graph31
mkdir -p build/graph_paths31
mkdir -p build/alignment31
mkdir -p build/tools31
mkdir -p build/commands31
mkdir -p build/tests31
cd libs; make
make[1]: Entering directory '/mccortex-0.2/libs'
make[1]: *** No rule to make target 'xxHash/Makefile', needed by 'xxHash'.  Stop.
make[1]: Leaving directory '/mccortex-0.2/libs'
Makefile:324: recipe for target 'libs/string_buffer/string_buffer.h' failed
make: *** [libs/string_buffer/string_buffer.h] Error 2
```
The provided solution of `git clone --recursive` is not relevant here as I am trying to install from the latest release source. Any ideas of how to fix this?
