### ISSUE TITLE
zero coverage genotyping

### ISSUE THREAD

**Issue by hcdenbakker** [mcveanlab/mccortex#57]
I was looking into vcf-genotyping and introduced a zero coverage locus:

`CP006053.1      4399342 .       A       C       .       PASS    BUBBLE=204;K33  K33R:K33A       .:.     0:0`

only to find it was called as the alternative allele when genotyped:

`CP006053.1      4399342 .       A       C       .       PASS    BUBBLE=204;K33  GT:K33R:K33A:GQ ./.:.:.:.       1/1:0:0:0`

I used this command:

`./mccortex63 vcfgeno --out out.vcf.gz --kcov 30 --ploidy 2 myvcf.cov.vcf`

**Comment by iqbal-lab** [comment]
Hey Henk

1.  in your first line you seem to have two samples, one with .:. and one with 0:0 - what does this mean? What is .:. in this line, I thought it was coverage?

2. The entry which genotypes the sample as 1/1 also has a zero for GQ - so there is no confidence in that genotype.

**Comment by hcdenbakker** [comment]
re 1: .:. is a remnant of a dummy sample (needed to introduce this to get a
vcf with all variable sites for an entire population), the last column
represents a real sample/coverage

re 2: Overlooked the zero GQ... thanks for pointing that out. I let the 1/1
genotype call distract me.
