### ISSUE TITLE
No output in vcfs directory.

### ISSUE THREAD

**Issue by IdaBonde** [mcveanlab/mccortex#59]
Hi

I am trying to use McCortex to find variant between two strains of yeast.
I have tried running it both with a reference and without using make-pipeline.pl and then make, but I don't get any output in the vcfs dir.

What I have done is:
With reference:
make-pipeline.pl -r ref.fa '31,41,51,61,71' output_dir V1vsV4_colour_list.tsv > my_job_script.mk
make -f my_job_script.mk CTXDIR=<mccortex_dir> MEM=40G NTHREADS=20

Without reference:
make-pipeline.pl '31,41,51,61,71' output_dir V1vsV4_colour_list.tsv > my_job_script.mk
make -f my_job_script.mk CTXDIR=<mccortex_dir> MEM=40G NTHREADS=20

The V1vsV4_colour_list.tsv file looks like:
V1      ../../trimmed/V1_S66_single.fastq.gz    ../../trimmed/V1_S66_R1_paired.fastq.gz:../../trimmed/V1_S66_R2_paired.fastq.gz .
V4      ../../trimmed/V4_S69_single.fastq.gz    ../../trimmed/V4_S69_R1_paired.fastq.gz:../../trimmed/V4_S69_R2_paired.fastq.gz .

When running with the reference I get output in the bubbles_links, graphs, links and ref directories for each of the kmers. Running without reference I get output in bubbles_links, bubbles_plain, graphs and links.
Looking at the log files I don't see any errors.
Do you have any idea where I could have gone wrong?

Best,
Ida

**Comment by noporpoise** [comment]
By default make just constructs the McCortex graph. To make VCFs you must request `vcfs`:

    make -f my_job_script.mk CTXDIR=<mccortex_dir> MEM=40G NTHREADS=20 vcfs

A reference is a requirement to construct a VCF file.

Apologies for the very delayed response.
