### ISSUE TITLE
long reads

### ISSUE THREAD

**Issue by jdmontenegro** [mcveanlab/mccortex#60]
Hi, does the mccortex graph allows the generation of links using corrected long reads (like PacBio or minion) instead of the short reads? I do not see why not, unless there is something obvious that I am forgetting. The real question would be if it would be able to build a graph from the long reads and if it can handle raw long reads.

Regards,

Juan Montenegro

**Comment by noporpoise** [comment]
Yes McCortex can handle long reads. Threading reads works best with error corrected reads.
