### ISSUE TITLE
Cygwin make fails due to missing _O_BINARY error in xxHash

### ISSUE THREAD

**Issue by rffrancon** [mcveanlab/mccortex#61]
This issue effects mccortex because of it's dependency on xxHash (https://github.com/Cyan4973/xxHash/tree/88c6ee1e4db6155dbe7047fed793cb8406b56086).

Original issue in xxHash repo (opened 16th of March 2017): https://github.com/Cyan4973/xxHash/issues/100

**Comment by noporpoise** [comment]
Thanks for pointing this issue out. I've removed xxHash from our dependencies in 01d43275ec7bff92f74360a41d8bc84928d62368. Will merge into master after the tests run.
