### ISSUE TITLE
Pjoin memory allocation error

### ISSUE THREAD

**Issue by carlyprior** [mcveanlab/mccortex#62]
When attempting to merge link files with the pjoin command I receive a 'Fatal Error: Out of memory'. I have tried to allocate as much as 522G using the -m (--memory) flag to no avail. It appears that, for the instance shown below, I am only being allocated 28.9M which is utilized before any merging can be done. This error has occurred regardless of the number of input files. 
Attached is the error file which contains my script:

[mccortex-pjoin-errorfile.txt](https://github.com/mcveanlab/mccortex/files/1209042/mccortex-pjoin-errorfile.txt)

**Comment by iqbal-lab** [comment]
Carly has pinged me about this. I'll email to ask for more info on input data. @noporpoise do you have any reaction, seen before?

**Comment by noporpoise** [comment]
Apologies for the delay @carlyprior.

It looks like you need to specify the number of kmers you expect with e.g. `-n 10M` for 10 million kmers. McCortex uses the memory limit (`-m`) as a max, and tries to use less when possible. Sorry this isn't the most convenient setup.

**Comment by carlyprior** [comment]
No worries @noporpoise.
-n fixed my issue. Thanks for the advice!
