### ISSUE TITLE
No reference option for bubbles/calls2vcf

### ISSUE THREAD

**Issue by carlyprior** [mcveanlab/mccortex#63]
I'm struggling to figure out how to run the calls2vcf command without a reference. I see that you need a 5' flank file in SAM or BAM format, but it is unclear how I am to achieve this without a reference as both BWA and Stampy require references.

**Comment by noporpoise** [comment]
The VCF format requires a reference. You need some coordinate system to place variants on.

**Comment by carlyprior** [comment]
I see. I don't have a reference genome so is there a way to use the output from bubbles to get a VCF? Sorry for my misunderstanding about calls2vcf.

**Comment by iqbal-lab** [comment]
You could have a fake reference where each bubble has its own chromosome number. Assume each chromosome starts at the beginning of the flank.
