### ISSUE TITLE
Creating cortex graph from more than two FASTQ files

### ISSUE THREAD

**Issue by winni2k** [mcveanlab/mccortex#65]
I have two paired-end FASTQ files and two unpaired FASTQ files from the same sequencing run (output from trimmomatic). I would like to create a single graph from all of these files.  So far I have tried to create three separate graphs (one for the paired-end reads, and two for the single end reads), but I can't figure out how to merge the three graphs into one using only one color.  Using the join command gives me one graph with three colors, but I want all data to be merged into one color.

Is this possible with mccortex?

**Comment by noporpoise** [comment]
Using the offset notation, you can load each graph into colour zero:

    mccortex join out.ctx 0:in1.ctx 0:in2.ctx 0:in3.ctx

The syntax is briefly described here: https://github.com/mcveanlab/mccortex/wiki/Join-command

**Comment by noporpoise** [comment]
I'm closing for this issue for now - please re-open or comment if it's not clear.

**Comment by winni2k** [comment]
Ah! Great.  I'm adding this example to the wiki page because I think that might be helpful.
