### ISSUE TITLE
Mysterious parameters for plot-covg-hist.R script

### ISSUE THREAD

**Issue by mbhall88** [mcveanlab/mccortex#68]
In the [workflow examples for plotting coverage distribution](https://github.com/mcveanlab/mccortex/wiki/Workflow-Examples#plot-coverage-distribution) you give an example of running this plot with 

```sh
scripts/plot-covg-hist.R covg.before_cleaning.csv covg.before_cleaning.pdf
```

However, when I do this I get an error saying I am missing two parameters `[<cutoff> [<kcov>]]`. What do these mean/do? Would be great if you could add a passage about this in the wiki.

**Comment by noporpoise** [comment]
The last two arguments were supposed to be optional but were required by a bug. They should now be optional again (`git pull` to get fixed version).

* `cutoff` is the cleaning cutoff used/proposed
* `kcov` is approximate kmer coverage of your sample (see https://github.com/mcveanlab/mccortex/wiki/Kmer-coverage)
