### ISSUE TITLE
Build without sudo apt install

### ISSUE THREAD

**Issue by DaveIstanto** [mcveanlab/mccortex#70]
Apologies in advance if this is not the right place to ask this question.

During the build process, it is stated that on linux:
`sudo apt install liblzma-dev libbz2-dev`
should be done for htslib dependency purposes.

However, in our local system, only the admin has the ability to use this command. Is there any alternative to this?

What has been done:
- Manually downloading both liblzma-dev and libbz2-dev using wget
- Installing both liblzma-dev and libbz2-dev
- Add both paths to $LD_LIBRARY_PATH variable

After these, running make all within cloned mccortex folder still results in error. Attached is the stderr/stdout of the make all command.

[McCortex Stdout and Stderr.txt](https://github.com/mcveanlab/mccortex/files/2177258/McCortex.Stdout.and.Stderr.txt)

Thank you very much

**Comment by winni2k** [comment]
You can try compiling mccortex in a conda environment. Try installing miniconda from [here](https://conda.io/miniconda.html). Then activate the environment and install libz with `conda install zlib`.
