### ISSUE TITLE
Release tar does not compile

### ISSUE THREAD

**Issue by winni2k** [mcveanlab/mccortex#71]
It appears that the most recent [v0.2](https://github.com/mcveanlab/mccortex/releases/tag/v0.2) release tar-ball does not contain the code in submodules. That makes it practically impossible to compile just from the tar-ball.  Being able to compile from the tar-ball would make packaging in conda easier, as I don't think the `--recursive` keyword has been [implemented in conda yet](https://github.com/conda/conda-build/pull/753).

**Comment by noporpoise** [comment]
I've created a new release and attached tar-ball and zip of the repo with dependencies: https://github.com/mcveanlab/mccortex/releases/tag/mccortex-1.0

Does that work?

**Comment by winni2k** [comment]
It looks like it does!
I can confirm that I can compile and run tests on a `Red Hat 4.8.5-28` and a `Mac OS 10.13.6` machine.
