### ISSUE TITLE
Release `1.0` tar compiles as version `v0.0.3-610-g400c0e3`

### ISSUE THREAD

**Issue by winni2k** [mcveanlab/mccortex#73]
Not sure this is a problem, but I could not help but notice that the mccortex version string reported by the compiled binary of the 1.0 release returns the version string `mccortex=v0.0.3-610-g400c0e3`.  I would expect the version string to contain `1.0.0`?

**Comment by noporpoise** [comment]
Fixed - thanks @winni2k.
