### ISSUE TITLE
mccortex31 check: report error if records incomplete. 

### ISSUE THREAD

**Issue by izaak-coleman** [mcveanlab/mccortex#84]
I just wanted a sanity check - because i'm running on an unstable cluster that kills processes randomly - will `mccortex31 check` test a .ctx to see whether some preceding `mccortex31` command successfully wrote all kmer records it intended to write to the .ctx? Or will it just check header corruption.  I can see how corruption in the head could be tested (there are two CORTEX tags bounding the head). But is there a similar structure to check all intended kmer records were written?

**Comment by iqbal-lab** [comment]
it checks all the records are ok; it can't check that it is a correctly built graph from the input data, but it checks that it is all valid

**Comment by izaak-coleman** [comment]
So, if `mccortex31 build` was writing a .ctx and killed during the write process (so, only half the records were output), assuming that all written records were ok, would `mccortex31 check` detect the corruption? Thanks for your reply!

**Comment by iqbal-lab** [comment]
Yes, that's one thing we use it for

**Comment by izaak-coleman** [comment]
Great! Thanks Professor Iqbal.
