### ISSUE TITLE
Sorted flag in .ctx header

### ISSUE THREAD

**Issue by izaak-coleman** [mcveanlab/mccortex#85]
Is there a byte flag in the .ctx header to specify whether the .ctx has been sorted, 
if so, which (nth) byte?

Many thanks!
Izaak

**Comment by winni2k** [comment]
There's a draft spec of the cortex format [here](https://github.com/mcveanlab/CortexJDK/blob/master/docs/ctx_spec.md). It does not look like the header contains the bit you are looking for.

**Comment by izaak-coleman** [comment]
Thanks @winni2k
