### ISSUE TITLE
Script availability in conda recipe

### ISSUE THREAD

**Issue by mbhall88** [mcveanlab/mccortex#94]
Hey,

There is a [bioconda package](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mccortex) for `mccortex`, which is great. But the scripts, such as `make-pipeline.pl` are not on PATH. If I (or yourselves) were to update the bioconda recipe to add these to the package, which scripts do you think would be necessary?

**Comment by winni2k** [comment]
Glad to hear that the conda package has found other users than myself! 

Why not at all the scripts? I didn't include them at the time because i had no use for them, but others might.

**Comment by mbhall88** [comment]
Sure. I guess the only thing will be updating the dependencies for the recipe. At a quick glance some scripts needs Perl, some need graphviz, some need python (and associated libraries), some need R...

**Comment by winni2k** [comment]
Yikes, sounds like a mess, but doable. I would only start with the scripts that are necessary. 

I don't know which ones are absolutely necessary. @kvg?

**Comment by winni2k** [comment]
I mean, i have used the mccortex conda package for years without any need for scripts. Why not create a separate conda package just for the scripts? It could depend on the package with the binary.

**Comment by mbhall88** [comment]
My personal use case was that I wanted to use the `make-pipeline.pl` script inside the biocontainer image that is built from the bioconda package. In hindsight I could just download that script and use it inside a conda env with mccortex installed... Maybe that is a better way of doing it rather than creating a new recipe?

**Comment by winni2k** [comment]
I think you should be just fine composing conda packages with the mccortex cons package. That package is just a binary if i recall correctly.
